Lee/implement visual3 submission functions
HanKyungSung/inviteyou pull request #117
Opened 2023-09-04 05:07 UTC by Hyukjoo-Lee

### Description
- Form Input Validation: created a validation for the input values.
- Calendar Event : Users can create a calendar event directly from the page.
- RSVP Modal: A new RSVP modal has been added to the visual 3 wedding page.
- Link to Map Button: A link to map has been added.
- Backend Routing: Implemented a PUT route for the visual 3 component.
- Image Modal: Users can now click on an image to view it in a larger modal.

2023-09-07 04:50 UTC, HanKyungSung requested changes
Currently, there is a problem with submitting the form.

<img width="640" alt="image" src="https://github.com/HanKyungSung/inviteyou/assets/25420417/1d65519d-408c-472b-8d0b-9527333a31fe">

2023-09-07 04:55 UTC, HanKyungSung commented on invitation-backend/src/controllers/rsvp.controller.ts
> +          name: name
not sure why there is a  tab. Can you take a look?

2023-09-07 04:55 UTC, HanKyungSung commented on invitation-backend/src/controllers/rsvp.controller.ts
> +          ...body
another tab here as well

2023-09-07 04:55 UTC, HanKyungSung commented on invitation-backend/src/controllers/rsvp.controller.ts
> +          name: name
another tab here as well

2023-09-07 04:55 UTC, HanKyungSung commented on invitation-backend/src/controllers/rsvp.controller.ts
> +          ...body
another tab here as well

2023-09-07 04:55 UTC, HanKyungSung commented on invitation-backend/src/controllers/rsvp.controller.ts
> +      name === undefined ||
I think the validation for checking `participate` is missing.

2023-09-07 05:43 UTC, Hyukjoo-Lee commented
### Description
- Solved a problem with submitting the form.
- Removed the unexpected tap in the code.
- Added a option for attendance.

2023-09-07 06:08 UTC, HanKyungSung requested changes
<img width="1575" alt="image" src="https://github.com/HanKyungSung/inviteyou/assets/25420417/d83b4d38-6b15-458e-89a2-da176277b6a1">

The form does not get reset after submit. I think we should reset the form.

2023-09-07 22:04 UTC, Hyukjoo-Lee commented
I added reset form feature after a form submission

2023-09-09 06:21 UTC, HanKyungSung approved these changes

2023-09-09 06:22 UTC, merged